//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.HoaUnityRos
{
    [Serializable]
    public class JointAngleMsg : Message
    {
        public const string k_RosMessageName = "hoa_unity_ros/JointAngle";
        public override string RosMessageName => k_RosMessageName;

        public float[] jointAnglesCollection;

        public JointAngleMsg()
        {
            this.jointAnglesCollection = new float[0];
        }

        public JointAngleMsg(float[] jointAnglesCollection)
        {
            this.jointAnglesCollection = jointAnglesCollection;
        }

        public static JointAngleMsg Deserialize(MessageDeserializer deserializer) => new JointAngleMsg(deserializer);

        private JointAngleMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.jointAnglesCollection, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.jointAnglesCollection);
            serializer.Write(this.jointAnglesCollection);
        }

        public override string ToString()
        {
            return "JointAngleMsg: " +
            "\njointAnglesCollection: " + System.String.Join(", ", jointAnglesCollection.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
