//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3UnityRos
{
    [Serializable]
    public class JointPositionMsg : Message
    {
        public const string k_RosMessageName = "ur3_unity_ros/JointPosition";
        public override string RosMessageName => k_RosMessageName;

        public float[] joint_position;

        public JointPositionMsg()
        {
            this.joint_position = new float[0];
        }

        public JointPositionMsg(float[] joint_position)
        {
            this.joint_position = joint_position;
        }

        public static JointPositionMsg Deserialize(MessageDeserializer deserializer) => new JointPositionMsg(deserializer);

        private JointPositionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_position, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joint_position);
            serializer.Write(this.joint_position);
        }

        public override string ToString()
        {
            return "JointPositionMsg: " +
            "\njoint_position: " + System.String.Join(", ", joint_position.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
