//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3UnityRos
{
    [Serializable]
    public class TrajPlannerResponse : Message
    {
        public const string k_RosMessageName = "ur3_unity_ros/TrajPlanner";
        public override string RosMessageName => k_RosMessageName;

        public float[] ros;

        public TrajPlannerResponse()
        {
            this.ros = new float[0];
        }

        public TrajPlannerResponse(float[] ros)
        {
            this.ros = ros;
        }

        public static TrajPlannerResponse Deserialize(MessageDeserializer deserializer) => new TrajPlannerResponse(deserializer);

        private TrajPlannerResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ros, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.ros);
            serializer.Write(this.ros);
        }

        public override string ToString()
        {
            return "TrajPlannerResponse: " +
            "\nros: " + System.String.Join(", ", ros.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
